version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/mentos
    overwrite: yes

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 180
      runas: ubuntu
